### ISSUE TITLE
Allow using only lowercase or camelCase in package name.

### ISSUE THREAD

**Issue by ExtroNovosib** [f2prateek/dart#114]
I now about Oracle Docs and Package naming convention, but...

When package name starts with a capital letter (com.company.appname.UI) I get:
Error:(5, 29) error: cannot find symbol class UI
Error:(9, 51) error: package UI does not exist

But for com.company.appname.uI or com.company.appname.ui all work fine.

**Comment by stephanenicolas** [comment]
@extronovosib, you should simply not do that. Stick to java conventions. By
using package name with upper case you actually make you build depending on
a UNIX* file system, and it's bad.

You can still make a PR to Dart to make your build work, but I strongly
advise you to change your package names to use lower case. And such PR
honestly would have no value except encouraging bad practices..

2016-05-15 3:02 GMT-07:00 ExtroNovosib <notifications@github.com>:
